hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm-app -- hypridle")
  hl.exec_cmd("uwsm-app -- mako")
  hl.exec_cmd("uwsm-app -- waybar")
  hl.exec_cmd("uwsm-app -- swayosd-server")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("uwsm-app -- swaybg -i ~/.config/omarchy/current/background -m fill")
  hl.exec_cmd("uwsm-app -- env GSK_RENDERER=cairo walker --gapplication-service")
  hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)

hl.exec_cmd("restore-hypr-toggles")
