# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, xdg-terminal-exec --dir="$(terminal-cwd)" tmux new
$terminal = kitty
$browser = /usr/bin/zen-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, $browser
bindd = SUPER SHIFT, F, File manager, exec, nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, launch-spotify
bindd = SUPER SHIFT, N, Editor, exec, launch-editor
bindd = SUPER SHIFT, T, Activity, exec, launch-btop
bindd = SUPER SHIFT, D, Docker, exec, launch-lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, launch-obsidian
bindd = SUPER SHIFT, slash, Passwords, exec, 1password

bindd = SUPER SHIFT, C, VSCodium, exec, /opt/vscodium-bin/bin/codium

