$color = rgba(30, 28, 24, 1)
$inner_color = rgba(30, 28, 24, 1)
$outer_color = rgba(244, 240, 225, 1)
$font_color = rgba(194, 189, 166, 1)
$placeholder_color = rgba(194, 189, 166, 0.7)
$check_color = rgba(244, 240, 225, 1)
